version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: steel-estimation-web-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
    networks:
      - steel-estimation-net
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  steel-estimation-net:
    driver: bridge