services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: steel-estimation-web:latest
    container_name: steel-estimation-web-dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # Database connection from environment variables (following Microsoft's pattern)
      - ConnectionStrings__DefaultConnection=${SQLCONNSTR_DefaultConnection}
      # OAuth Settings
      - Authentication__Microsoft__ClientId=${MICROSOFT_CLIENT_ID}
      - Authentication__Microsoft__ClientSecret=${MICROSOFT_CLIENT_SECRET}
      # Google Maps API
      - GoogleMaps__ApiKey=${GOOGLE_MAPS_API_KEY}
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - steel-estimation-net
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  steel-estimation-net:
    driver: bridge