name: Deploy to Sandbox

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-steel-estimation-prod
  AZURE_WEBAPP_SLOT: staging
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: 
      name: Sandbox
      url: https://app-steel-estimation-prod-staging.azurewebsites.net
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish SteelEstimation.Web/SteelEstimation.Web.csproj -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
        package: ./publish

    - name: Create deployment summary
      if: success()
      run: |
        echo "## 🚀 Deployment Successful!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** Sandbox/Staging" >> $GITHUB_STEP_SUMMARY
        echo "**URL:** https://app-steel-estimation-prod-staging.azurewebsites.net" >> $GITHUB_STEP_SUMMARY
        echo "**Branch:** develop" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "**Deployed by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "**Time:** $(date)" >> $GITHUB_STEP_SUMMARY